# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddURLLevel0():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.delete_all_cookies()
  
  def teardown_method(self, method):
    self.driver.quit()
    print('\n')
  
  def test_success(self):
    self.driver.get("https://school.moodledemo.net/course/modedit.php?add=url&type&course=69&section=0&return=0&sr=0&beforemod=0")
    self.driver.find_element(By.CSS_SELECTOR, ".login > a").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "username").send_keys("teacher")
    time.sleep(2)
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    time.sleep(2)
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "setmode").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "id_name").send_keys("URL")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_externalurl").send_keys("https://www.overleaf.com")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_submitbutton").click()
    time.sleep(2)
    assert self.driver.title == "MCC : URL | Mount Orange School"

  def test_fail_1(self):
    self.driver.get("https://school.moodledemo.net/course/modedit.php?add=url&type&course=69&section=0&return=0&sr=0&beforemod=0")
    self.driver.find_element(By.CSS_SELECTOR, ".login > a").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "username").send_keys("teacher")
    time.sleep(2)
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    time.sleep(2)
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "setmode").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "id_name").send_keys("")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_externalurl").send_keys("https://www.overleaf.com")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_submitbutton").click()
    time.sleep(2)
    assert self.driver.title == "Editing URL | Mount Orange School"

  def test_fail_2(self):
    self.driver.get("https://school.moodledemo.net/course/modedit.php?add=url&type&course=69&section=0&return=0&sr=0&beforemod=0")
    self.driver.find_element(By.CSS_SELECTOR, ".login > a").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "username").send_keys("teacher")
    time.sleep(2)
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    time.sleep(2)
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "setmode").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "id_name").send_keys("URL")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_externalurl").send_keys("")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_submitbutton").click()
    time.sleep(2)
    assert self.driver.title == "Editing URL | Mount Orange School"

  def test_fail_3(self):
    self.driver.get("https://school.moodledemo.net/course/modedit.php?add=url&type&course=69&section=0&return=0&sr=0&beforemod=0")
    self.driver.find_element(By.CSS_SELECTOR, ".login > a").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "username").send_keys("teacher")
    time.sleep(2)
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    time.sleep(2)
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "setmode").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "id_name").send_keys("")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_externalurl").send_keys("")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_submitbutton").click()
    time.sleep(2)
    assert self.driver.title == "Editing URL | Mount Orange School"

  def test_fail_4(self):
    self.driver.get("https://school.moodledemo.net/course/modedit.php?add=url&type&course=69&section=0&return=0&sr=0&beforemod=0")
    self.driver.find_element(By.CSS_SELECTOR, ".login > a").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "username").send_keys("teacher")
    time.sleep(2)
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    time.sleep(2)
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "setmode").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "id_name").send_keys("URL")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_externalurl").send_keys("Link")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_submitbutton").click()
    time.sleep(2)
    assert self.driver.title == "Editing URL | Mount Orange School"

  def test_fail_5(self):
    self.driver.get("https://school.moodledemo.net/course/modedit.php?add=url&type&course=69&section=0&return=0&sr=0&beforemod=0")
    self.driver.find_element(By.CSS_SELECTOR, ".login > a").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "username").send_keys("teacher")
    time.sleep(2)
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    time.sleep(2)
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "setmode").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "id_name").send_keys("")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_externalurl").send_keys("Link")
    time.sleep(2)
    self.driver.find_element(By.ID, "id_submitbutton").click()
    time.sleep(2)
    assert self.driver.title == "Editing URL | Mount Orange School"
  

