# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import read_write_excel as rwe

class TestAddURLLevel1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.delete_all_cookies()
  
  def teardown_method(self, method):
    self.driver.quit()
    print('\n')
  
  def add_url(self, url, name, input_url):
    self.driver.get(url)
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".login > a").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "username").send_keys("teacher")
    time.sleep(2)
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    time.sleep(2)
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "setmode").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "id_name").send_keys(name)
    time.sleep(2)
    self.driver.find_element(By.ID, "id_externalurl").send_keys(input_url)
    time.sleep(2)
    self.driver.find_element(By.ID, "id_submitbutton").click()
    time.sleep(2)
    return self.driver.title

  @pytest.mark.parametrize('function, url, name, input_url, expected_result',
                            rwe.read_from_excel(r'../test_data.xlsx', 'add_url'))
  def test_func_add_url(self, function, url, name, input_url, expected_result):
    expected = expected_result.split('|')[0]
    actual = self.add_url(url, name, input_url).split('|')[0]

    assert expected in actual


